name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "$SERVER_SSH_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r . $SERVER_USERNAME@$SERVER_HOST:/path/to/deployment/folder
          ssh -i key.pem $SERVER_USERNAME@$SERVER_HOST 'cd /path/to/deployment/folder && npm install && pm2 restart app'

  # Optional: Send a notification on success/failure
  notification:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Notify success
        if: success()
        run: echo "Build and deployment succeeded."
      - name: Notify failure
        if: failure()
        run: echo "Build or deployment failed."
